CREATE TABLE `weapon` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC));


CREATE TABLE `player_weapon_stats` (
  `PLAYER_ID` INT NOT NULL,
  `SERVER_ID` INT NOT NULL,
  `WEAPON_ID` INT NOT NULL,
  `KILLS` INT NULL,
  `HEADSHOTS` INT NULL,
  `SHOTS` INT NULL,
  `HITS` INT NULL,
  PRIMARY KEY (`PLAYER_ID`, `SERVER_ID`),
  UNIQUE INDEX `WEAPON_PLAYER_SERVER_UNIQUE` (`WEAPON_ID`, `SERVER_ID`, `PLAYER_ID`),
  CONSTRAINT `player_weapon_stats_wp_id` FOREIGN KEY (`WEAPON_ID`) REFERENCES `stats`.`weapon` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION);

INSERT INTO `stats_version` (`version`) VALUES (1);
